[project]
name = "medisana-blood-pressure"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "homeassistant>=2024.12.5",
    "ruff>=0.12.4",
]


#  mac_address: "A4:C1:38:C6:B3:C5"