name: Mypy Type Check (uv + pyproject.toml)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mypy:
    name: Run mypy using uv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: taiki-e/install-action@v2
        with:
          tool: uv

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project with uv
        run: |
          uv pip install .  # Installiert Abhängigkeiten aus pyproject.toml
          uv pip install mypy types-requests  # falls nicht schon in pyproject.toml

      - name: Run mypy
        run: |
          mypy 
