name: Mypy Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mypy:
    name: Run mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # gleiche Version wie Home Assistant Core

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy types-requests  # ggf. weitere Typ-Stubs

      - name: Run mypy
        run: |
          mypy custom_components/
