name: Mypy Type Check (uv + pyproject.toml)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mypy:
    name: Run mypy using uv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project with uv
        run: |
          uv pip install .  # Installiert dein Projekt + Abhängigkeiten
          uv pip install mypy types-requests  # falls nötig

      - name: Run mypy
        run: |
          mypy
